name: Bug Report
description: Report a bug in an example project
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Found an issue with one of the examples? Let us know.

  - type: dropdown
    id: example
    attributes:
      label: Example
      description: Which example is affected?
      options:
        - basic-agent
        - multi-llm
        - custom-tools
        - sub-agents
        - context-management
        - coding-assistant
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your system info
      placeholder: |
        - OS: macOS 15 / Ubuntu 24.04 / Windows 11
        - Node.js: 22.x
      render: markdown
